# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert a categorical time-series into multivariate indicator process
#'
#' @param xt
#' @return yt
#' @examples
NULL

cat_convert_c <- function(xt) {
    .Call('_EnvSca_cat_convert_c', PACKAGE = 'EnvSca', xt)
}

#' Given a m times p-1 categorical time series, compute:
#' (1) the Fourier frequencies
#' (2) the spectral envelope
#' (3) the optimal scaling
#'
NULL

env_get_c <- function(yt, fyy) {
    .Call('_EnvSca_env_get_c', PACKAGE = 'EnvSca', yt, fyy)
}

#'
#' Given a several time series within a group
#' Compute
#' (1) the group level spectral envelope
#' (2) the group level optimal scaling
#'
NULL

group_env_c <- function(yt_group, L) {
    .Call('_EnvSca_group_env_c', PACKAGE = 'EnvSca', yt_group, L)
}

