# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cat_convert_c <- function(xt) {
    .Call(`_EnvSca_cat_convert_c`, xt)
}

env_get_c <- function(yt, fyy) {
    .Call(`_EnvSca_env_get_c`, yt, fyy)
}

group_env_c <- function(yt_group, L) {
    .Call(`_EnvSca_group_env_c`, yt_group, L)
}

