# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_cat_convert <- function(xt) {
    .Call('_EnvSca_cpp_cat_convert', PACKAGE = 'EnvSca', xt)
}

