# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'

      - name: Generate code coverage badge
        if: matrix.config.os == 'ubuntu-latest' && matrix.config.r == 'release' # Run on only one configuration
        run: |
          Rscript -e '
          library(covr);
          library(badger);
          coverage <- package_coverage();
          coverage_percentage <- percent_coverage(coverage);
          badge_custom(
            label = "code-coverage",
            value = paste0(coverage_percentage, "%"),
            color = ifelse(coverage_percentage >= 80, "brightgreen",
                    ifelse(coverage_percentage >= 50, "yellow", "red")),
            path = "man/figures/code-coverage-badge.svg"
          );
          '

      - name: Commit and push coverage badge
        if: matrix.config.os == 'ubuntu-latest' && matrix.config.r == 'release' # Run on only one configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add man/figures/code-coverage-badge.svg
          git commit -m "Update code coverage badge"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
